### ISSUE TITLE
jQuery Core 1.9 Upgrade Guide

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/impersonate#113]
# jQuery Core 1.9 Upgrade Guide

Changes of Note in jQuery 1.9
See the full [upgrade guide at jquery.com](http://jquery.com/upgrade-guide/1.9/)

## Minor

`.data()`

- [ ] /js/impersonate.js

`.parents()`

- [ ] /js/impersonate.js

`.attr()`

- [ ] /js/settings-admin.js

`.insertBefore()`

- [ ] /js/impersonate_logout.js

`.insertAfter()`

- [ ] /js/impersonate.js

**Comment by sharidas** [comment]
Created PR https://github.com/owncloud/impersonate/pull/114, as its required to show impersonate icon.
Also applied the changes mentioned at https://github.com/owncloud/core/issues/31739#issuecomment-396869330.
Below are the tests conducted:
- login as admin user
- created 3 users `user1`, `user2`, `user3` 
- enabled impersonate
- Navigated to user management page
- Impersonate icon appeared for `user1`, `user2` and `user3`.
- created a group `group1` and added users `user1` and `user2`  to the group. `user1` and `user3` are the group admin for `group1`
- Whitelisted the group `group1` in the Settings -> User Authentication page.
- Now tried to impersonate `user1` successfully. Was able to see impersonate icon only for `user2`.
- Now tried to impersonate `user2`. Didn't allowed further impersonation. Expected behavior.
- Logged out and reached back to `admin`.
- Logged in as `user3` and was able to see impersonate icon for `user1` and `user2`.

**Comment by sharidas** [comment]
This works as expected. Provided we would have to merge the change:
- https://github.com/owncloud/impersonate/pull/114
and will have to bring change as mentioned in https://github.com/owncloud/core/issues/31739#issuecomment-396869330

**Comment by PVince81** [comment]
the change was merged, anything else ?

**Comment by PVince81** [comment]
regarding https://github.com/owncloud/core/issues/31739#issuecomment-396869330, please test against stable10 instead if possible

**Comment by sharidas** [comment]
Yes other than https://github.com/owncloud/core/issues/31739#issuecomment-396869330, from the impersonate apps perspective nothing blocks. 

Closing this ticket as https://github.com/owncloud/impersonate/pull/114 is merged.
